language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t prerana/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true prerana/docker-react npm run test    